#!/usr/bin/env bash
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
out=$(mktemp)
trap 'rm -f "$out"' EXIT

cat >"$out" <<'EOF'
// Generated by scripts/generate-unified-wcl.sh from the standalone template
// definitions. Edit the per-template vmlab.wcl files, then regenerate.

import <vmlab.wcl>

// The empty lab makes this repository discoverable by vmlab-web. Template
// builds are driven from the Templates tab; there are no ordinary lab VMs.
lab "templates" { }
EOF

while IFS= read -r file; do
  dir=${file#./}
  dir=${dir%/vmlab.wcl}
  {
    printf '\n// -----------------------------------------------------------------------------\n'
    printf '// %s\n\n' "$dir"
    sed \
      -e '/^[[:space:]]*import <vmlab\.wcl>[[:space:]]*$/d' \
      -e "s#from = \"\./#from = \"./$dir/#g" \
      -e "s#path = \"\./#path = \"./$dir/#g" \
      -e 's#path = "\.\./iso/#path = "./iso/#g' \
      -e "s#provision \"scripts/#provision \"$dir/scripts/#g" \
      -e "s#first_boot = \"scripts/#first_boot = \"$dir/scripts/#g" \
      "$file"
  } >>"$out"
done < <(cd "$root" && find . -mindepth 2 -maxdepth 2 -name vmlab.wcl \
  -not -path './examples/*' -print | sort)

mv "$out" "$root/vmlab.wcl"
trap - EXIT
