#!/usr/bin/env bash
# Generate docs/data/templates.gen.wcl from the registry + in-repo vmlab.wcl.
#
# Enumeration: `vmlab template search --json` against the ghcr registry; when
# that yields nothing (registry private/unauthed/not-yet-pushed) we fall back to
# the in-repo template dirs so the site always builds. Hardware specs always come
# from each template's vmlab.wcl. Presentation copy is NOT touched here — it is
# hand-authored in docs/data/meta.wcl and joined at render time by short-name.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/data/templates.gen.wcl"
REGISTRY="ghcr.io/vmlabdev/vmlab-templates"

cd "$ROOT"

# field VALUE from a vmlab.wcl: `key = value` or `key = "value"`.
field() { sed -nE "s/^[[:space:]]*$2[[:space:]]*=[[:space:]]*\"?([^\"]*)\"?[[:space:]]*\$/\1/p" "$1" | head -n1; }
# "10GiB" -> "10 GiB", "512MiB" -> "512 MiB"
pretty() { sed -E 's/([0-9])(GiB|MiB|KiB|TiB|GB|MB|KB)/\1 \2/' <<<"$1"; }
slug()   { tr -c 'A-Za-z0-9' '_' <<<"$1" | sed -E 's/_+/_/g; s/^_|_$//g'; }

# Published short-names from the registry (best effort). published[name]=version
declare -A published=()
if command -v vmlab >/dev/null 2>&1; then
  if json="$(vmlab template search --registry "$REGISTRY" --json 2>/dev/null)" && [ -n "$json" ]; then
    while IFS=$'\t' read -r nm ver; do
      [ -n "$nm" ] && published["$nm"]="$ver"
    done < <(printf '%s' "$json" | jq -r '.[] | [.name, .version] | @tsv' 2>/dev/null || true)
  fi
fi
[ "${#published[@]}" -gt 0 ] && echo "registry: ${#published[@]} published template(s)" >&2 \
  || echo "registry: none reachable — falling back to in-repo vmlab.wcl dirs" >&2

emit() {  # $1 = template dir
  local dir="$1" f="$1/vmlab.wcl"
  [ -f "$f" ] || return 0
  local arch reg short ver profile cpus mem disk
  arch="$(field "$f" arch)";       reg="$(field "$f" registry)"
  short="${reg##*/}";              [ -n "$short" ] || short="$dir"
  ver="$(field "$f" version)";     profile="$(field "$f" profile)"
  cpus="$(field "$f" cpus)";       [ -n "$cpus" ] || cpus=1
  mem="$(pretty "$(field "$f" memory)")"
  disk="$(pretty "$(field "$f" disk)")"
  # If the registry was reachable, only emit published templates and prefer the
  # published version tag.
  if [ "${#published[@]}" -gt 0 ]; then
    [ -n "${published[$short]+x}" ] || return 0
    ver="${published[$short]}"
  fi
  local id name updated
  id="$(slug "${arch}/${short}")"
  name="${arch}/${short}"
  updated="$(git log -1 --format=%cd --date=format:'%Y-%m-%d' -- "$dir" 2>/dev/null || true)"
  [ -n "$updated" ] || updated="—"
  cat >>"$OUT" <<WCL
tpl $id {
  name       = "$name"
  short_name = "$short"
  arch       = "$arch"
  version    = "$ver"
  profile    = "$profile"
  cpus       = $cpus
  memory     = "$mem"
  disk       = "$disk"
  registry   = "$reg"
  updated    = "$updated"
  source_dir = "$dir"
}
WCL
}

mkdir -p "$ROOT/docs/data"
cat >"$OUT" <<'HDR'
// GENERATED by docs/gen-data.sh (`just docs-data`). DO NOT EDIT.
// Registry/repo facts only; presentation copy lives in docs/data/meta.wcl.

import "../schema.wcl"

HDR

for d in */vmlab.wcl; do emit "${d%/vmlab.wcl}"; done

n="$(grep -c '^tpl ' "$OUT" || true)"
echo "wrote $n tpl record(s) -> ${OUT#$ROOT/}" >&2
